// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import {defineConfig} from "prisma/config";

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // TRY-BRANCH(match-smart): pinned to this branch's isolated DB copy (see lib/prisma.ts).
    url: "file:./prisma/beyondledger-smart.db",
  },
});